travis:
  secure:
    BINSTAR_TOKEN: i7xQoPFQ8Unj347/19aPfKTEbTaqzrUvjxlRkfNtEmlLeJq6o2GJGwqjRGbDB6hOxeA4j+pQ0TIntPwQZn+yfu0A9P617+Hyit6kPbcDer8dX67BSXFFt901FpHoAgPGJg2k8/DS7cpQLdX+sLY1Nqr1W2aT6j+XVybohm41GUVgV9wYhSCU0gYWpw9Y3MZ12j7YbysivX6EOFoVz2VWwSKAziVR8Ad82h3clLd4S3u8ZK2n5acJIKcovQYNr8bZALzij+94Top6k1nBpAgVNy1LslN2n6VhSNKobkMfasf+SsBD/PLLA+PD6xubDh8Gk6U3U/ZpnNKP00viNiOX4HpPmkoGOkbhbqeVwqKbgIXdpuvd3HASjVbHIQjZgw0j1YIytapsoZYFwroN1AMhFmwC8qsvcOWsNNhrtIGVkoFQAP0ht2bWX40/o8qq0SrxDSFfRK7VGO+aDP1Csp/XMOFx/aOO4RWbfoXUzKP5spVftyEiHD1+nK9IM/QdvrTJ+S+2pdzh65jFNPgo4ri2aFFgxhQWzD4bKvlsaCxlUvZylWDUwQrXQjqXxUKdN/R7be2I9LmibrPvQoHnJlgffeeWZbpG/NSt4mxOe2fmZa96cRVhq+4AG+vokH4ldnt422xD2DJr7fFev389j6VXvpr/aA0pZxTLBE4//Dbvt9U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
